name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Executa quando houver push na branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use a versão do Node que preferir

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build # O script de build já está configurado no package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # A pasta que o 'npm run build' gera
